import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { GradientPalette, MeshGradient } from "@blur-ui/mesh-gradient";
import { Background } from "@/components/ui/background";
import { Header } from "@/components/ui/header";
import { Providers } from "@/components/providers";
import {Toaster} from "react-hot-toast"
import '@rainbow-me/rainbowkit/styles.css'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const colors: GradientPalette = {
  color1: "#1B262E",
  color2: "#213741",
  color3: "#327547",
  color4: "#72FB9D",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased bg-gradient-to-r from-gradient-start to-gradient-end flex flex-col`}
      >
        <Providers>
          <Header />
          {children}
          <Toaster/>
        </Providers>
        <Background />
      </body>
    </html>
  );
}
